# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and load artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i - production
    - run: npm run build --if-present
    - run: mkdir .to_deploy
    - run: cp -r build .to_deploy/build
    - run: cp -r static .to_deploy/static
    - run: cp -r views .to_deploy/views
    - run: cp package.json .to_deploy
  
    - uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: last_build
        # A file, directory or wildcard pattern that describes what to upload
        path: .to_deploy/
